name: List Repositories and Commit

on:
 workflow_dispatch:

jobs:
  list_repos_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@users.noreply.github.com"

      - name: Clone repository using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          gh repo clone ${{ github.repository }} --branch ${{ github.ref }} --depth 1

      - name: Change to cloned repo directory
        run: |
          cd ${{ github.event.repository.name }}

      - name: List Repositories
        run: |
          curl -s https://api.github.com/users/${{ github.actor }}/repos | jq '.[].name' > out/repo_list.txt

      - name: Create out directory if it doesn't exist
        run: |
          mkdir -p out

      - name: Commit and push changes
        run: |
          git add out/repo_list.txt
          git commit -m "Update repo_list.txt"
          git push
