name: List Public Repositories
on:
  workflow_dispatch:
jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: List Repositories
      run: |
        curl -s https://api.github.com/users/${{ github.actor }}/repos | jq '.[].name' > $GITHUB_WORKSPACE/out/repo_list.txt
    - name: Display Repositories
      run: |
        echo "Public Repositories:"
        cat $GITHUB_WORKSPACE/out/repo_list.txt
