name: List Public Repositories
on:
  workflow_dispatch:
jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: List Repositories
      run: |
        curl -s https://api.github.com/users/brettjrea/repos | jq '.[].name' > repo_list.txt
    - name: Display Repositories
      run: |
        echo "Public Repositories:"
        cat repo_list.txt
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: repo-list
        path: repo_list.txt
