name: Export Non-Failed Workflow Runs

on:
  workflow_dispatch:

jobs:
  list-non-failed-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List non-failed workflow runs and save to file
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          mkdir -p out
          page=1
          echo "ID,Status,Conclusion,Workflow Name" > out/non_failed_runs.txt
          while : ; do
            response=$(gh api -X GET "/repos/$GITHUB_REPOSITORY/actions/runs?per_page=100&page=$page")
            if [ -z "$(echo "$response" | jq -r '.workflow_runs[]')" ]; then
              break
            fi
            echo "$response" | jq -r '.workflow_runs[] | select((.status != "completed") or (.conclusion != "failure")) | [.id, .status, .conclusion, .name] | @tsv' >> out/non_failed_runs.txt
            page=$((page+1))
          done

      - name: Commit and push the non-failed runs file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add out/non_failed_runs.txt
          git commit -m "Add non-failed runs list" -a || echo "No changes to commit"
          git push || echo "No changes to push"
