name: List Public Repositories
on:
  workflow_dispatch:
jobs:
  list-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Create out directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/out
    - name: List Repositories
      run: |
        curl -s https://api.github.com/users/${{ github.actor }}/repos | jq '.[].name' > $GITHUB_WORKSPACE/out/repo_list.txt
    - name: Commit Changes
      uses: elstudio/actions-git-commit@v2.5.0
      with:
        branch: ${{ github.ref }}
        message: "Added repo_list.txt"
        files: |
          out/repo_list.txt
        name: ${{ github.actor }}
        email: ${{ github.actor }}@users.noreply.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
