name: Pair old scripts and markdown then export.
on:
  workflow_dispatch:

jobs:
  find_old_files:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        script_file_type: [sh, ps1]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find and pair .old files
      run: |
        # Loop through each file type in the matrix and find and pair the corresponding .old files
        for script_type in ${{ matrix.script_file_type }}; do
          # Create the output directories if they don't exist
          mkdir -p out/paired
          mkdir -p out/unpaired

          # Initialize the output files
          paired_output_file="${{ github.workspace }}/out/paired/paired_old_files_$script_type.md"
          unpaired_output_file="${{ github.workspace }}/out/unpaired/unpaired_old_files_$script_type.md"
          echo "#### List of .old file pairs for .$script_type" > "$paired_output_file"
          echo "#### List of unpaired .old files for .$script_type" > "$unpaired_output_file"

          # Find all .old script files and store them in a temporary file
          find . -type f -name "*.$script_type.old" > old_script_files_temp.txt

          # Add this line to verify that the correct files are being found
          find . -type f -name "*.$script_type.old"

          # Pair .old script files with corresponding .md.old files and write them to the output file
          while read -r old_script_file; do
            base_name=$(basename "$old_script_file" .$script_type.old)
            md_old_file=$(find . -type f -iname "$base_name.md.old")
            if [[ -n "$md_old_file" ]]; then
              echo "<a href=\"$old_script_file\">$old_script_file</a><br>" >> "$paired_output_file"
              echo "<a href=\"$md_old_file\">$md_old_file</a><br>" >> "$paired_output_file"
              echo "" >> "$paired_output_file"
            else
              echo "<a href=\"$old_script_file\">$old_script_file</a><br>" >> "$unpaired_output_file"
              echo "" >> "$unpaired_output_file"
            fi
          done < old_script_files_temp.txt
        done

    - name: Stash changes
      run: git stash

    - name: Fetch and rebase
      run: |
        git fetch origin main
        git rebase origin/main

    - name: Apply stash
      run: git stash apply

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update paired_old_files.md and unpaired_old_files.md with .old files"
        file_pattern: "out/**/*.md"
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Replace ${{ secrets.GITHUB_TOKEN }} with the personal access token that you created in the repository settings.
