name: Remove Failed Runs

on:
  workflow_dispatch:

jobs:
  remove-failed-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove failed runs
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"
          gh run list --json id,status,conclusion --repo $GITHUB_REPOSITORY \
            | jq -r '.[] | select(.status=="completed" and .conclusion=="failure") | .id' \
            | xargs -I {} gh run cancel {} --force \
            && \
          gh run list --json id,status,conclusion --repo $GITHUB_REPOSITORY \
            | jq -r '.[] | select(.status=="completed" and .conclusion=="failure") | .id' \
            | xargs -I {} gh run delete {} --force
