name: watch readme

env:
  REPO_NAME: brettjrea/Windows_WSL_Debian
  WINDOWS_INSTALL_FILE: readme/windows-install-wsl.md
  DEBIAN_UPGRADE_FILE: readme/debian-bullseye-upgrade-script.md

on:
  workflow_dispatch:
  push:
    paths:
      - ${{ env.WINDOWS_INSTALL_FILE }}
      - ${{ env.DEBIAN_UPGRADE_FILE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Dispatch event if a watched file was modified
        if: ${{ contains([env.WINDOWS_INSTALL_FILE, env.DEBIAN_UPGRADE_FILE], steps.changed-files.outputs.modified_files) }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.REPO_NAME }}
          event-type: file-changed
          client-payload: '{ "message": "${{ github.event_name }}: ${{ steps.changed-files.outputs.modified_files }} modified" }'
