name: Watch Readme Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'readme/windows-install-wsl.md'
      - 'readme/debian-bullseye-upgrade-script.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: "true"

      - name: Debug changed-files output
        run: echo "${{ steps.changed-files.outputs.json }}"

      - name: Trigger repository dispatch
        if: >
          ${{ contains(fromJson(steps.changed-files.outputs.json).modified, 'readme/windows-install-wsl.md') }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: brettjrea/Windows_WSL_Debian
          event-type: file-changed
          client-payload: '{ "message": "windows-install-wsl.md changed" }'

      - name: Trigger repository dispatch
        if: >
          ${{ contains(fromJson(steps.changed-files.outputs.json).modified, 'readme/debian-bullseye-upgrade-script.md') }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: brettjrea/Debian_Bullseye_Upgrade_Script
          event-type: file-changed
          client-payload: '{ "message": "debian-bullseye-upgrade-script.md changed" }'
