name: Watch Readme Files

on:
  push:
    # Trigger only if any of these files are modified
    paths:
      - 'readme/generate-readme-table-of-contents.md'
      - 'readme/windows-install-wsl.md'
      - 'readme/debian-bullseye-upgrade-script.md'
      - 'readme/ubuntu-jammy-upgrade-script.md'
      - 'readme/debian-install-nvm.md'
      - 'readme/debian-install-nvs.md'
      - 'readme/debian-install-common-build-tools.md'
      - 'readme/debian-strapi-backend-api.md'
      - 'readme/debian-gatsby-frontend-client.md'
      - 'readme/gatsby-typescript-styled-components.md'
      - 'readme/debian-configure-pm2.md'
      - 'readme/debian-install-github-cli.md'
      
env:
  BASE_PATH: ''
  FILENAME: ''

jobs:
  get_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set base path
        run: |
          export BASE_PATH=$(dirname "${{ github.event.head_commit.modified[0] }}")
          export FILENAME=$(basename "${{ github.event.head_commit.modified[0] }}")
      - name: Print base path
        run: |
          echo "BASE_PATH=$BASE_PATH"
          
  build:
    runs-on: ubuntu-latest
    needs: get_base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Debug
        run: echo ${{ toJson(github.event.head_commit.modified) }}
        
      - name: Trigger Single Repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          # Use the repo name from the path of the modified file
          repository: brettjrea/$BASE_PATH
          event-type: file-changed
          client-payload: '{ "message": "File ${{ env.BASE_PATH }}/${{ env.FILENAME }} has been modified" }'
