name: watch readme 

on:
  workflow_dispatch:
  push:
    paths:
      - 'readme/windows-install-wsl.md'
      - 'readme/debian-bullseye-upgrade-script.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Run a step if readme/windows-install-wsl.md was modified
        if: contains(steps.changed-files.outputs.modified_files, 'readme/windows-install-wsl.md')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: brettjrea/Windows_WSL_Debian
          event-type: file-changed
          client-payload: '{ "message": "windows-install-wsl.md changed" }'
          
      - name: Run a step if readme/debian-bullseye-upgrade-script.md was modified
        if: contains(steps.changed-files.outputs.modified_files, 'readme/debian-bullseye-upgrade-script.md')
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: brettjrea/Windows_WSL_Debian
          event-type: file-changed
          client-payload: '{ "message": "readme/debian-bullseye-upgrade-script.md" }'
 
