on:
  workflow_dispatch:
  push:
    paths:
      - 'readme/windows-install-wsl.md'
      - 'readme/debian-bullseye-upgrade-script.md'

env:
  REPOSITORY_MAPPING: '{ "readme/windows-install-wsl.md": "brettjrea/Windows_WSL_Debian", "readme/debian-bullseye-upgrade-script.md": "myusername/myrepo" }'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v5
        
      - name: Notify repository update
        if: ${{ github.event_name == 'push' || contains(steps.changed-files.outputs.modified_files, 'readme/') }}
        run: |
          echo "${{ github.event_name }}: repository update"
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            repository=$(echo ${{ fromJson('{"mapping":' + (env.REPOSITORY_MAPPING | fromJson) + '}') }} | jq -r '.mapping["'${file}'"]')
            echo "File '${file}' was modified. Notifying repository '${repository}'."
            curl -X POST \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${repository}/dispatches" \
              -d '{"event_type": "file-changed", "client_payload": { "message": "'"${file}"' changed" }}'
          done
