on:
  push:
    # Trigger only if any of these files are modified
    paths:
      - 'readme/generate-readme-table-of-contents.md'
      
env:
  REPO_NAME: ''

jobs:
  get_repo_name:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository name
        run: |
          export REPO_NAME=$(echo "${{ github.repository }}" | cut -d/ -f2)
          echo "REPO_NAME=$REPO_NAME"

  trigger_dispatch:
    runs-on: ubuntu-latest
    needs: get_repo_name
    steps:
      - name: Trigger Single Repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: brettjrea/${{ env.REPO_NAME }}
          event-type: file-changed
          client-payload: '{ "message": "File ${{ github.event.inputs.filename }} has been modified" }'
