name: Watch Readme Files

on:
  push:
    paths:
      - 'readme/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          windows-install-wsl.md: brettjrea/Windows_WSL_Debian
          debian-bullseye-upgrade-script.md: brettjrea/Debian_Bullseye_Upgrade_Script
          ubuntu-jammy-upgrade-script.md: brettjrea/Ubuntu_Jammy_Upgrade_Script
          debian-install-nvm.md: brettjrea/Debian_Install_NVM
          debian-install-nvs.md: brettjrea/Debian_Install_NVS
          debian-install-common-build-tools.md: brettjrea/Debian_Install_Common_Build_Tools
          debian-strapi-backend-api.md: brettjrea/Debian_Strapi_Backend_API
          debian-gatsby-frontend-client.md: brettjrea/Debian_Gatsby_Frontend_Client
          gatsby-typescript-styled-components.md: brettjrea/Gatsby_Typescript_Styled_Components
          debian-configure-pm2.md: brettjrea/Debian_Configure_PM2
          debian-install-github-cli.md: brettjrea/Debian_Install_GitHub_CLI
    steps:
      - name: Trigger Single Repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: file-changed
          client-payload: '{ "message": "${{ matrix.repo }}: ${{ github.event_path }} changed" }'
