name: Remove Failed Runs

on:
  workflow_dispatch:

jobs:
  remove-failed-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove failed runs
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          export GH_TOKEN_HEADER="Authorization: token $GITHUB_TOKEN"
          gh run list --json id,status,conclusion --repo $GITHUB_REPOSITORY --header "$GH_TOKEN_HEADER" \
            | jq -r '.[] | select(.status=="completed" and .conclusion=="failure") | .id' \
            | xargs -I {} gh run cancel {} --force --header "$GH_TOKEN_HEADER" \
            && \
          gh run list --json id,status,conclusion --repo $GITHUB_REPOSITORY --header "$GH_TOKEN_HEADER" \
            | jq -r '.[] | select(.status=="completed" and .conclusion=="failure") | .id' \
            | xargs -I {} gh run delete {} --force --header "$GH_TOKEN_HEADER"
