name: Remove Failed Runs

on:
  workflow_dispatch:

jobs:
  remove-failed-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove failed runs
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          gh api -X GET "/repos/$GITHUB_REPOSITORY/actions/runs?status=completed" -q ".workflow_runs[] | select(.conclusion == \"failure\") | .id" \
            | xargs -I {} gh api -X DELETE "/repos/$GITHUB_REPOSITORY/actions/runs/{}"
