on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  REPOSITORY_MAPPING: '{ "readme/windows-install-wsl.md": "brettjrea/Windows_WSL_Debian", "readme/debian-bullseye-upgrade-script.md": "brettjrea/Debian_Bullseye_Upgrade_Script" }'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v5

      - name: Extract file name
        id: extract-file
        run: |
          MODIFIED_FILES=$(echo "${{ steps.changed-files.outputs.modified_files }}" | tr -d '\n')
          FILENAME=$(echo "$MODIFIED_FILES" | head -n1)
          echo "::set-output name=filename::$FILENAME"

      - name: Extract repository name
        id: extract-repo
        run: |
          FILENAME="${{ steps.extract-file.outputs.filename }}"
          REPO=$(echo "$REPOSITORY_MAPPING" | jq -r '."'"$FILENAME"'"')
          if [[ -z "$REPO" ]]; then
            echo "::warning::No repository found for file $FILENAME"
            echo "::set-output name=repository::none"
          else
            echo "::set-output name=repository::$REPO"
          fi

      - name: Run a step if a file was modified
        if: steps.changed-files.outputs.modified_files != '' && steps.extract-repo.outputs.repository != 'none'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ steps.extract-repo.outputs.repository }}
          event-type: file-changed
          client-payload: '{ "message": "A file was modified" }'

      - name: Report if no dispatches were sent
        if: steps.changed-files.outputs.modified_files != '' && steps.extract-repo.outputs.repository == 'none'
        run: |
          echo "::warning::No repository found for any modified files"
          echo "::set-output name=no-dispatches-sent::true"
