name: Watch Readme Files

on:
 workflow_dispatch:
 push:
    paths:     
      - 'readme/generate-readme-table-of-contents.md'
      - 'readme/debian-generate-readme.md'
      - 'readme/debian-bullseye-upgrade-script.md'
      - 'readme/ubuntu-jammy-upgrade-script.md'
      - 'readme/debian-install-nvm.md'
      - 'readme/debian-install-nvs.md'
      - 'readme/debian-install-common-build-tools.md'
      - 'readme/debian-strapi-backend-api.md'
      - 'readme/debian-gatsby-frontend-client.md'
      - 'readme/gatsby-typescript-styled-components.md'
      - 'readme/debian-configure-pm2.md'
      - 'readme/debian-install-github-cli.md'
      - 'readme/windows-install-wsl.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Debug
       env:
         MODIFIED: ${{ toJson(github.event.head_commit.modified) }}
       run: echo $MODIFIED

     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Bullseye_Upgrade_Script
        event-type: file-changed
        client-payload: '{ "message": "debian-bullseye-upgrade-script.md changed" }' 
     
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Ubuntu_Jammy_Upgrade_Script
        event-type: file-changed
        client-payload: '{ "message": "ubuntu-jammy-upgrade-script.md changed" }'
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Install_NVM
        event-type: file-changed
        client-payload: '{ "message": "debian-install-nvm.md changed" }'  
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Install_NVS
        event-type: file-changed
        client-payload: '{ "message": "debian-install-nvs.md changed" }'
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Install_Common_Build_Tools
        event-type: file-changed
        client-payload: '{ "message": "debian-install-common-build-tools.md changed" }'
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Strapi_Backend_API
        event-type: file-changed
        client-payload: '{ "message": "debian-strapi-backend-api.md changed" }'
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Gatsby_Frontend_Client
        event-type: file-changed
        client-payload: '{ "message": "debian-gatsby-frontend-client.md changed" }'
      
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Gatsby_Typescript_Styled_Components
        event-type: file-changed
        client-payload: '{ "message": "gatsby-typescript-styled-components.md changed" }' 

     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Configure_PM2
        event-type: file-changed
        client-payload: '{ "message":"debian-configure-pm2.md changed" }'
    
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Debian_Install_GitHub_CLI
        event-type: file-changed
        client-payload: '{ "message":"debian-install-github-cli.md changed" }'
        
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Windows_WSL_Debian
        event-type: file-changed
        client-payload: '{ "message":"windows-install-wsl.md changed" }'
    


