name: Watch Powershell Files

on:
 workflow_dispatch:
 push:
    paths:     
      - 'powershell/windows-install-wsl.ps1'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Debug
       env:
         MODIFIED: ${{ toJson(github.event.head_commit.modified) }}
       run: echo $MODIFIED
       
     - name: Trigger Single Repository
       uses: peter-evans/repository-dispatch@v2
       with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: brettjrea/Windows_WSL_Debian
        event-type: file-changed
        client-payload: '{ "message":"windows-install-wsl.ps1 changed" }'
