on:
  workflow_dispatch:
  push:

env:
  REPOSITORY_MAPPING: >-
    {
    "readme/windows-install-wsl.md": "brettjrea/Windows_WSL_Debian",
    "readme/debian-bullseye-upgrade-script.md": "brettjrea/Debian_Bullseye_Upgrade_Script",
    "readme/ubuntu-jammy-upgrade-script.md": "brettjrea/Ubuntu_Jammy_Upgrade_Script",
    "readme/debian-install-nvm.md": "brettjrea/Debian_Install_NVM",
    "readme/debian-install-nvs.md": "brettjrea/Debian_Install_NVS",
    "readme/debian-install-common-build-tools.md": "brettjrea/Debian_Install_Common_Build_Tools",
    "readme/debian-strapi-backend-api.md": "brettjrea/Debian_Strapi_Backend_API",
    "readme/debian-gatsby-frontend-client.md": "brettjrea/Debian_Gatsby_Frontend_Client",
    "readme/gatsby-typescript-styled-components.md": "brettjrea/Gatsby_Typescript_Styled_Components",
    "readme/debian-configure-pm2.md": "brettjrea/Debian_Configure_PM2",
    "readme/debian-install-github-cli.md": "brettjrea/Debian_Install_GitHub_CLI"
    }


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Extract file name
        id: extract-file
        run: |
          MODIFIED_FILES=$(echo "${{ steps.changed-files.outputs.modified_files }}" | tr -d '\n')
          FILENAME=$(echo "$MODIFIED_FILES" | head -n1)
          echo "::set-output name=filename::$FILENAME"

      - name: Extract repository name
        id: extract-repo
        run: |
          FILENAME="${{ steps.extract-file.outputs.filename }}"
          REPO=$(echo "$REPOSITORY_MAPPING" | jq -r '."'"$FILENAME"'"')
          echo "::set-output name=repository::$REPO"

      - name: Run a step if a file was modified
        if: steps.changed-files.outputs.modified_files != ''
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ steps.extract-repo.outputs.repository }}
          event-type: file-changed
          client-payload: '{ "message": "A file was modified" }'
